/**
 * FFIEC Call Report field code → { label, category }
 *
 * Covers all codes present in the 2024 bulk download (files 1 and 2).
 * Codes prefixed RCFD = Consolidated D+F, RCON = Domestic only, RIAD = Income.
 *
 * KEY_METRICS: the subset that gets its own typed column in the `financials` table.
 * Everything else is stored in the `raw_data` JSONB column.
 */

const CATEGORIES = {
  BALANCE_SHEET: 'Balance Sheet',
  LOANS: 'Loans & Leases',
  PAST_DUE: 'Past Due & Nonaccrual',
  SECURITIES: 'Securities',
  DEPOSITS: 'Deposits',
  BORROWINGS: 'Borrowings & Liabilities',
  EQUITY: 'Equity Capital',
  INCOME: 'Income Statement',
  TRADING: 'Trading Assets',
  OTHER: 'Other',
};

// -------------------------------------------------------------------
// Named columns (stored as individual typed fields on `financials`)
// -------------------------------------------------------------------
const KEY_METRICS = {
  total_assets:    { codes: ['RCFD2170', 'RCON2170'], label: 'Total Assets', category: CATEGORIES.BALANCE_SHEET },
  total_deposits:  { codes: ['RCFN2200', 'RCFD2200', 'RCON2200'], label: 'Total Deposits', category: CATEGORIES.DEPOSITS },
  total_equity:    { codes: ['RCFD3210', 'RCON3210'], label: 'Total Equity Capital', category: CATEGORIES.EQUITY },
  net_loans:       { codes: ['RCFD2122', 'RCON2122'], label: 'Loans & Leases, Net', category: CATEGORIES.LOANS },
  net_income:      { codes: ['RIAD4340'], label: 'Net Income', category: CATEGORIES.INCOME },
  interest_income: { codes: ['RIAD4010'], label: 'Total Interest & Fee Income on Loans', category: CATEGORIES.INCOME },
  past_due_30_89:  { codes: ['RCFD1406', 'RCON1406'], label: 'Total Past Due 30–89 Days (Accruing)', category: CATEGORIES.PAST_DUE },
  past_due_90_plus:{ codes: ['RCFD1407', 'RCON1407'], label: 'Total Past Due 90+ Days (Accruing)', category: CATEGORIES.PAST_DUE },
  goodwill:        { codes: ['RCFD3163', 'RCON3163'], label: 'Goodwill', category: CATEGORIES.BALANCE_SHEET },
};

// -------------------------------------------------------------------
// Full label map for all 426 codes in the 2024 dataset
// Format: CODE → { label, category }
// -------------------------------------------------------------------
const FIELD_MAP = {
  // ── Balance Sheet ─────────────────────────────────────────────────
  RCFD0071: { label: 'Int-Bearing Bals Due From Dep Institutions', category: CATEGORIES.BALANCE_SHEET },
  RCFD0081: { label: 'Noninterest-Bearing Bals, Currency & Coin', category: CATEGORIES.BALANCE_SHEET },
  RCFD2130: { label: 'Loans & Leases Held for Sale', category: CATEGORIES.LOANS },
  RCFD2143: { label: 'Other Identifiable Intangible Assets', category: CATEGORIES.BALANCE_SHEET },
  RCFD2145: { label: 'Premises & Fixed Assets (Incl. Cap. Leases)', category: CATEGORIES.BALANCE_SHEET },
  RCFD2150: { label: 'Other Real Estate Owned', category: CATEGORIES.BALANCE_SHEET },
  RCFD2160: { label: 'Other Assets', category: CATEGORIES.BALANCE_SHEET },
  RCFD2170: { label: 'Total Assets', category: CATEGORIES.BALANCE_SHEET },
  RCFD3000: { label: 'Invest. in Unconsolidated Subs & Associates', category: CATEGORIES.BALANCE_SHEET },
  RCFD3123: { label: 'Allowance for Loan & Lease Losses (ALLL)', category: CATEGORIES.LOANS },
  RCFD3163: { label: 'Goodwill', category: CATEGORIES.BALANCE_SHEET },
  RCFD3190: { label: 'Other Borrowed Money', category: CATEGORIES.BORROWINGS },
  RCFD3200: { label: 'Subordinated Notes & Debentures', category: CATEGORIES.BORROWINGS },
  RCFD3210: { label: 'Total Equity Capital', category: CATEGORIES.EQUITY },
  RCFD3230: { label: 'Common Stock', category: CATEGORIES.EQUITY },
  RCFD3300: { label: 'Total Liabilities, Reserves & Capital Accts', category: CATEGORIES.BALANCE_SHEET },
  RCFD3505: { label: 'Federal Funds Sold in Domestic Offices', category: CATEGORIES.BALANCE_SHEET },
  RCFD3506: { label: 'Securities Purchased Under Agreements to Resell', category: CATEGORIES.SECURITIES },
  RCFD3507: { label: 'Securities Sold Under Agreements to Repurchase', category: CATEGORIES.BORROWINGS },
  RCFD3529: { label: 'Total Trading Assets', category: CATEGORIES.TRADING },
  RCFD3530: { label: 'Trading Liabilities', category: CATEGORIES.TRADING },
  RCFD3545: { label: 'Perpetual Preferred Stock & Related Surplus', category: CATEGORIES.EQUITY },
  RCFD3548: { label: 'Surplus', category: CATEGORIES.EQUITY },
  RCFD3632: { label: 'Goodwill (Schedule RC)', category: CATEGORIES.BALANCE_SHEET },
  RCFD3656: { label: 'Undivided Profits & Capital Reserves', category: CATEGORIES.EQUITY },
  RCFD3838: { label: 'Direct & Indirect Investments in Real Estate', category: CATEGORIES.BALANCE_SHEET },
  RCFD3839: { label: 'Other Components of Equity Capital', category: CATEGORIES.EQUITY },
  RCFD6724: { label: 'Federal Funds Purchased in Domestic Offices', category: CATEGORIES.BORROWINGS },
  RCFDA130: { label: 'Accumulated Other Comprehensive Income', category: CATEGORIES.EQUITY },
  RCFDB989: { label: 'Loans & Leases, Net Unearned Income', category: CATEGORIES.LOANS },
  RCFDB995: { label: 'Loans & Leases, Net Unearned Income & Allowance', category: CATEGORIES.LOANS },
  RCFDC240: { label: 'Minority Interest in Consolidated Subsidiaries', category: CATEGORIES.EQUITY },
  RCFDC241: { label: 'Total Equity Capital Incl. Noncontrolling Interest', category: CATEGORIES.EQUITY },
  RCFDC410: { label: 'Total Loans Restructured in Troubled Debt (Current)', category: CATEGORIES.LOANS },
  RCFDC411: { label: 'Total Loans Restructured in Troubled Debt (Past Due)', category: CATEGORIES.LOANS },
  RCFDG105: { label: 'Total Liabilities', category: CATEGORIES.BORROWINGS },
  RCFDJJ34: { label: 'Additions to Nonaccrual Assets', category: CATEGORIES.PAST_DUE },
  RCFDJA22: { label: 'Nonaccrual Assets Sold During Quarter', category: CATEGORIES.PAST_DUE },
  RCFDPV23: { label: 'Audit Indicator', category: CATEGORIES.OTHER },
  RCFDPV24: { label: 'Fiscal Year End', category: CATEGORIES.OTHER },
  RCFDPV25: { label: 'Last Date/Time Submission Accepted', category: CATEGORIES.OTHER },

  // ── Securities ────────────────────────────────────────────────────
  RCFD2930: { label: 'Held-to-Maturity Securities', category: CATEGORIES.SECURITIES },
  RCFD2948: { label: 'Available-for-Sale Securities', category: CATEGORIES.SECURITIES },

  // ── Loans ─────────────────────────────────────────────────────────
  RCFD1773: { label: 'Loans & Leases, Net (Domestic)', category: CATEGORIES.LOANS },
  RCFD2122: { label: 'Loans & Leases, Net Unearned Inc. & Allowance', category: CATEGORIES.LOANS },
  RCFDB528: { label: 'Closed-End Loans Secured 1st Liens, Past Due 30-89d', category: CATEGORIES.LOANS },
  RCFDB529: { label: 'Closed-End Loans Secured 1st Liens, Past Due 90d+', category: CATEGORIES.LOANS },
  RCFDB530: { label: 'Closed-End Loans Secured 1st Liens, Nonaccrual', category: CATEGORIES.LOANS },
  RCFDB575: { label: 'Closed-End Loans Secured Jr Liens, Past Due 30-89d', category: CATEGORIES.LOANS },
  RCFDB576: { label: 'Closed-End Loans Secured Jr Liens, Past Due 90d+', category: CATEGORIES.LOANS },
  RCFDB577: { label: 'Closed-End Loans Secured Jr Liens, Nonaccrual', category: CATEGORIES.LOANS },
  RCFDC226: { label: 'Loans & Leases Held for Sale, Nonaccrual', category: CATEGORIES.LOANS },
  RCFDF166: { label: 'Fair Value Loan HFS, Past Due 30-89d', category: CATEGORIES.LOANS },
  RCFDF167: { label: 'Fair Value Loan HFS, Past Due 90d+', category: CATEGORIES.LOANS },
  RCFDF168: { label: 'Fair Value Loan HFS, Nonaccrual', category: CATEGORIES.LOANS },
  RCFDF169: { label: 'Unpaid Bal Loan HFS, Past Due 30-89d', category: CATEGORIES.LOANS },
  RCFDF170: { label: 'Unpaid Bal Loan HFS, Past Due 90d+', category: CATEGORIES.LOANS },
  RCFDF171: { label: 'Unpaid Bal Loan HFS, Nonaccrual', category: CATEGORIES.LOANS },

  // ── Past Due & Nonaccrual ─────────────────────────────────────────
  RCFD1248: { label: 'Lns Secured by RE to Non-US Addr, Past Due 30d', category: CATEGORIES.PAST_DUE },
  RCFD1249: { label: 'Lns Secured by RE to Non-US Addr, Past Due 90d', category: CATEGORIES.PAST_DUE },
  RCFD1250: { label: 'Lns Secured by RE to Non-US Addr, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD1251: { label: 'C&I Loans to US Addr, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFD1252: { label: 'C&I Loans to US Addr, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCFD1253: { label: 'C&I Loans to US Addr, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD1254: { label: 'C&I Loans to Non-US Addr, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFD1255: { label: 'C&I Loans to Non-US Addr, Past Due 90 Days', category: CATEGORIES.PAST_DUE },
  RCFD1256: { label: 'C&I Loans to Non-US Addr, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD1403: { label: 'Total, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD1406: { label: 'Total, Past Due 30-89 Days, Accruing', category: CATEGORIES.PAST_DUE },
  RCFD1407: { label: 'Total, Past Due 90 or More, Accruing', category: CATEGORIES.PAST_DUE },
  RCFD1583: { label: 'Loans to Farmers, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD1594: { label: 'Loans to Farmers, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFD1597: { label: 'Loans to Farmers, Past Due 90 or More', category: CATEGORIES.PAST_DUE },
  RCFD5369: { label: 'Lns Secured by Farmland, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFD5377: { label: 'Lns Secured by Farmland, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFD5378: { label: 'Lns Secured by Farmland, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD5379: { label: 'Lns Secured by Multifamily, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFD5380: { label: 'Lns Secured by Multifamily, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFD5381: { label: 'Lns Secured by Multifamily, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD5382: { label: 'Commercial RE, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFD5389: { label: 'Commercial RE, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCFD5390: { label: 'Commercial RE, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD5391: { label: 'Revolving Open-End Loans, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFD5459: { label: 'Revolving Open-End Loans, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFD5460: { label: 'Revolving Open-End Loans, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD5461: { label: 'Other Assets, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFD6558: { label: 'Other Assets, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCFD6559: { label: 'Other Assets, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFD6560: { label: 'Lns to US Banks, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFDHK26: { label: 'Lns to Foreign Banks, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCFDHK27: { label: 'Lns to Foreign Banks, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCFDHK28: { label: 'Lns to Foreign Banks, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFDK036: { label: 'Past Due 30-89d: Credit Card Loans (Household)', category: CATEGORIES.PAST_DUE },
  RCFDK037: { label: 'Past Due 90d+: Credit Card Loans (Household)', category: CATEGORIES.PAST_DUE },
  RCFDK038: { label: 'Nonaccrual: Credit Card Loans (Household)', category: CATEGORIES.PAST_DUE },
  RCFDK039: { label: 'Past Due 30-89d: Auto Loans to Individuals', category: CATEGORIES.PAST_DUE },
  RCFDK040: { label: 'Past Due 90d+: Auto Loans to Individuals', category: CATEGORIES.PAST_DUE },
  RCFDK041: { label: 'Nonaccrual: Auto Loans to Individuals', category: CATEGORIES.PAST_DUE },
  RCFDK042: { label: 'Past Due 30-89d: Other Consumer Loans', category: CATEGORIES.PAST_DUE },
  RCFDK043: { label: 'Past Due 90d+: Other Consumer Loans', category: CATEGORIES.PAST_DUE },
  RCFDK044: { label: 'Nonaccrual: Other Consumer Loans', category: CATEGORIES.PAST_DUE },
  RCFDK102: { label: 'Past Due 30-89d: Lease Financing Receivables', category: CATEGORIES.PAST_DUE },
  RCFDK103: { label: 'Past Due 90d+: Lease Financing Receivables', category: CATEGORIES.PAST_DUE },
  RCFDK104: { label: 'Nonaccrual: Lease Financing Receivables', category: CATEGORIES.PAST_DUE },
  RCFDK120: { label: 'Past Due 30-89d: Lns to Foreign Govts & Instits', category: CATEGORIES.PAST_DUE },
  RCFDK121: { label: 'Past Due 90d+: Lns to Foreign Govts & Instits', category: CATEGORIES.PAST_DUE },
  RCFDK122: { label: 'Nonaccrual: Lns to Foreign Govts & Instits', category: CATEGORIES.PAST_DUE },
  RCFDK123: { label: 'Past Due 30-89d: All Other Loans', category: CATEGORIES.PAST_DUE },
  RCFDK124: { label: 'Past Due 90d+: All Other Loans', category: CATEGORIES.PAST_DUE },
  RCFDK125: { label: 'Nonaccrual: All Other Loans', category: CATEGORIES.PAST_DUE },
  RCFDK126: { label: 'Repl Cost of Contracts, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFDK127: { label: 'Repl Cost of Contracts, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFDK128: { label: 'Repl Cost of Contracts, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFDK138: { label: 'Past Due 30-89d: Purchased Credit-Improved Lns (Bal)', category: CATEGORIES.PAST_DUE },
  RCFDK139: { label: 'Past Due 90d+: Purchased Credit-Improved Lns (Bal)', category: CATEGORIES.PAST_DUE },
  RCFDK140: { label: 'Nonaccrual: Purchased Credit-Improved Lns (Bal)', category: CATEGORIES.PAST_DUE },
  RCFDK213: { label: 'Past Due 30-89d: Purchased Credit-Improved Lns (Carry)', category: CATEGORIES.PAST_DUE },
  RCFDK214: { label: 'Past Due 90d+: Purchased Credit-Improved Lns (Carry)', category: CATEGORIES.PAST_DUE },
  RCFDK215: { label: 'Nonaccrual: Purchased Credit-Improved Lns (Carry)', category: CATEGORIES.PAST_DUE },
  RCFDK216: { label: 'Lns Guaranteed US Excl FDIC, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFDK217: { label: 'Lns Guaranteed US Excl FDIC, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFDK218: { label: 'Lns Guaranteed US Excl FDIC, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFDK274: { label: 'GNMA Rebooked Lns Repurchased, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFDK275: { label: 'GNMA Rebooked Lns Repurchased, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFDK276: { label: 'GNMA Rebooked Lns Repurchased, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFDK277: { label: 'Loss-Share FDIC All Other Lns/Leases, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFDK278: { label: 'Loss-Share FDIC All Other Lns/Leases, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFDK279: { label: 'Loss-Share FDIC All Other Lns/Leases, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCFDK280: { label: 'Loss-Share FDIC Covered Loss-Sharing, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCFDK281: { label: 'Loss-Share FDIC Covered Loss-Sharing, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCFDK282: { label: 'Loss-Share FDIC Covered Loss-Sharing, Nonaccrual', category: CATEGORIES.PAST_DUE },

  // ── Deposits ──────────────────────────────────────────────────────
  RCFN2200: { label: 'Total Deposits', category: CATEGORIES.DEPOSITS },
  RCFN6631: { label: 'Non-Interest Bearing Deposits', category: CATEGORIES.DEPOSITS },
  RCFN6636: { label: 'Total Interest-Bearing Deposits (Dom. & Foreign)', category: CATEGORIES.DEPOSITS },
  RCFNB572: { label: 'Past Due 30-89d: Loans in Foreign Offices', category: CATEGORIES.PAST_DUE },
  RCFNB573: { label: 'Past Due 90d+: Loans in Foreign Offices', category: CATEGORIES.PAST_DUE },
  RCFNB574: { label: 'Nonaccrual: Loans in Foreign Offices', category: CATEGORIES.PAST_DUE },

  // ── RCON (Domestic Only) ──────────────────────────────────────────
  RCON0071: { label: 'Int-Bearing Bals Due From Dep Institutions (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON0081: { label: 'Noninterest-Bearing Bals, Currency & Coin (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON1226: { label: 'Lns Secured by RE to Non-US Addr, Past Due 30d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1227: { label: 'Lns Secured by RE to Non-US Addr, Past Due 90d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1228: { label: 'Lns Secured by RE to Non-US Addr, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1248: { label: 'Lns Secured by RE to Non-US Addr, Past Due 30d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1249: { label: 'Lns Secured by RE to Non-US Addr, Past Due 90d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1250: { label: 'Lns Secured by RE to Non-US Addr, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1254: { label: 'C&I Lns to Non-US Addr, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1255: { label: 'C&I Lns to Non-US Addr, Past Due 90d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1256: { label: 'C&I Lns to Non-US Addr, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1403: { label: 'Total, Nonaccrual (Domestic)', category: CATEGORIES.PAST_DUE },
  RCON1406: { label: 'Total, Past Due 30-89 Days, Accruing (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1407: { label: 'Total, Past Due 90 or More, Accruing (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1583: { label: 'Loans to Farmers, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1594: { label: 'Loans to Farmers, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1597: { label: 'Loans to Farmers, Past Due 90+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1606: { label: 'Past Due 30-89d: C&I Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1607: { label: 'Past Due 90d+: C&I Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1608: { label: 'Nonaccrual: C&I Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCON1773: { label: 'Loans & Leases, Net (Domestic)', category: CATEGORIES.LOANS },
  RCON2130: { label: 'Loans & Leases Held for Sale (Dom)', category: CATEGORIES.LOANS },
  RCON2143: { label: 'Other Identifiable Intangible Assets (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON2145: { label: 'Premises & Fixed Assets (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON2150: { label: 'Other Real Estate Owned (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON2160: { label: 'Other Assets (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON2170: { label: 'Total Assets (Domestic)', category: CATEGORIES.BALANCE_SHEET },
  RCON2200: { label: 'Total Deposits (Dom)', category: CATEGORIES.DEPOSITS },
  RCON2930: { label: 'Held-to-Maturity Securities (Dom)', category: CATEGORIES.SECURITIES },
  RCON2948: { label: 'Available-for-Sale Securities (Dom)', category: CATEGORIES.SECURITIES },
  RCON3000: { label: 'Invest. in Unconsolidated Subs (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON3123: { label: 'ALLL Amount (Dom)', category: CATEGORIES.LOANS },
  RCON3163: { label: 'Goodwill (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON3190: { label: 'Other Borrowed Money (Dom)', category: CATEGORIES.BORROWINGS },
  RCON3200: { label: 'Subordinated Notes & Debentures (Dom)', category: CATEGORIES.BORROWINGS },
  RCON3210: { label: 'Total Equity Capital (Dom)', category: CATEGORIES.EQUITY },
  RCON3230: { label: 'Common Stock (Dom)', category: CATEGORIES.EQUITY },
  RCON3300: { label: 'Total Liabilities, Reserves & Capital (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON3493: { label: 'Lns Secured by Farmland, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3494: { label: 'Lns Secured by Farmland, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3495: { label: 'Lns Secured by Farmland, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3499: { label: 'Lns Secured by Multifamily, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3500: { label: 'Lns Secured by Multifamily, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3501: { label: 'Lns Secured by Multifamily, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON3505: { label: 'Federal Funds Sold (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON3506: { label: 'Securities Purchased Under Resell Agreements (Dom)', category: CATEGORIES.SECURITIES },
  RCON3507: { label: 'Securities Sold Under Repurchase Agreements (Dom)', category: CATEGORIES.BORROWINGS },
  RCON3545: { label: 'Perpetual Preferred Stock (Dom)', category: CATEGORIES.EQUITY },
  RCON3548: { label: 'Surplus (Dom)', category: CATEGORIES.EQUITY },
  RCON3632: { label: 'Goodwill (Dom, RC)', category: CATEGORIES.BALANCE_SHEET },
  RCON3656: { label: 'Undivided Profits & Capital Reserves (Dom)', category: CATEGORIES.EQUITY },
  RCON3838: { label: 'Direct & Indirect Investments in Real Estate (Dom)', category: CATEGORIES.BALANCE_SHEET },
  RCON3839: { label: 'Other Components of Equity Capital (Dom)', category: CATEGORIES.EQUITY },
  RCON5369: { label: 'Commercial RE, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5380: { label: 'Commercial RE, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5381: { label: 'Commercial RE, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5382: { label: 'Revolving Open-End Loans, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5398: { label: 'Revolving Open-End Loans, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5399: { label: 'Revolving Open-End Loans, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5400: { label: 'All Other Loans, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5459: { label: 'All Other Loans, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5460: { label: 'All Other Loans, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON5461: { label: 'Other Assets, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON6558: { label: 'Other Assets, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCON6559: { label: 'Other Assets, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCON6560: { label: 'Lns to Foreign Banks, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCON6631: { label: 'Non-Interest Bearing Deposits (Dom)', category: CATEGORIES.DEPOSITS },
  RCON6636: { label: 'Total Interest-Bearing Deposits (Dom)', category: CATEGORIES.DEPOSITS },
  RCON6724: { label: 'Federal Funds Purchased (Dom)', category: CATEGORIES.BORROWINGS },
  RCON8678: { label: 'Loans & Leases Held for Sale, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONA130: { label: 'Accumulated Other Comprehensive Income (Dom)', category: CATEGORIES.EQUITY },
  RCONB528: { label: 'Closed-End Loans 1st Liens, Past Due 30-89d (Dom)', category: CATEGORIES.LOANS },
  RCONB529: { label: 'Closed-End Loans 1st Liens, Past Due 90d+ (Dom)', category: CATEGORIES.LOANS },
  RCONB530: { label: 'Closed-End Loans 1st Liens, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONB575: { label: 'Closed-End Loans Jr Liens, Past Due 30-89d (Dom)', category: CATEGORIES.LOANS },
  RCONB576: { label: 'Closed-End Loans Jr Liens, Past Due 90d+ (Dom)', category: CATEGORIES.LOANS },
  RCONB577: { label: 'Closed-End Loans Jr Liens, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONB834: { label: 'Lease Individual HH/Family, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONB835: { label: 'Lease Individual HH/Family, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONB836: { label: 'Lease Individual HH/Family, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONB987: { label: 'All Other Lease, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCONB989: { label: 'Loans & Leases Net Unearned Income (Dom)', category: CATEGORIES.LOANS },
  RCONB993: { label: 'All Other Lease, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCONB995: { label: 'Loans & Leases Net Unearn Inc & Allow (Dom)', category: CATEGORIES.LOANS },
  RCONC226: { label: 'Loans & Leases HFS, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONC229: { label: 'HFS, Past Due 30-89 Days', category: CATEGORIES.PAST_DUE },
  RCONC230: { label: 'HFS, Past Due 90 Days or More', category: CATEGORIES.PAST_DUE },
  RCONC236: { label: 'All Other Lease, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONC237: { label: 'Lns to US Bks Etc, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONC238: { label: 'Lns to US Bks Etc, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONC239: { label: 'Lns to US Bks Etc, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONC240: { label: 'Minority Interest in Consolidated Subsidiaries (Dom)', category: CATEGORIES.EQUITY },
  RCONC241: { label: 'Total Equity Incl. Noncontrolling Interest (Dom)', category: CATEGORIES.EQUITY },
  RCONC410: { label: 'Total Loans Restructured TDR (Current, Dom)', category: CATEGORIES.LOANS },
  RCONC411: { label: 'Total Loans Restructured TDR (Past Due, Dom)', category: CATEGORIES.LOANS },
  RCONF166: { label: 'Fair Value Loan HFS, Past Due 30-89d (Dom)', category: CATEGORIES.LOANS },
  RCONF167: { label: 'Fair Value Loan HFS, Past Due 90d+ (Dom)', category: CATEGORIES.LOANS },
  RCONF168: { label: 'Fair Value Loan HFS, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONF172: { label: 'Past Due 30-89d: Credit Card Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF173: { label: 'Past Due 90d+: Credit Card Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF174: { label: 'Nonaccrual: Credit Card Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF175: { label: 'Past Due 30-89d: Lns/Leases to DI (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF176: { label: 'Past Due 90d+: Lns/Leases to DI (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF177: { label: 'Nonaccrual: Lns/Leases to DI (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF178: { label: 'Unpaid Bal Loan HFS, Past Due 30-89d (Dom)', category: CATEGORIES.LOANS },
  RCONF179: { label: 'Unpaid Bal Loan HFS, Past Due 90d+ (Dom)', category: CATEGORIES.LOANS },
  RCONF180: { label: 'Unpaid Bal Loan HFS, Nonaccrual (Dom)', category: CATEGORIES.LOANS },
  RCONF181: { label: 'Purchased Credit-Improved Lns Bal, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF182: { label: 'Purchased Credit-Improved Lns Bal, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF183: { label: 'Purchased Credit-Improved Lns Bal, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF661: { label: 'Purchased Credit-Improved Lns Carry, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF662: { label: 'Purchased Credit-Improved Lns Carry, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONF663: { label: 'Purchased Credit-Improved Lns Carry, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONG105: { label: 'Total Liabilities (Dom)', category: CATEGORIES.BORROWINGS },
  RCONHK26: { label: 'Lns to Foreign Banks, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONHK27: { label: 'Lns to Foreign Banks, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONHK28: { label: 'Lns to Foreign Banks, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONJA22: { label: 'Nonaccrual Assets Sold During Quarter (Dom)', category: CATEGORIES.PAST_DUE },
  RCONJJ34: { label: 'Additions to Nonaccrual Assets (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK036: { label: 'Past Due 30-89d: Credit Card Lns Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK037: { label: 'Past Due 90d+: Credit Card Lns Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK038: { label: 'Nonaccrual: Credit Card Lns Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK039: { label: 'Past Due 30-89d: Auto Loans Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK040: { label: 'Past Due 90d+: Auto Loans Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK041: { label: 'Nonaccrual: Auto Loans Household (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK042: { label: 'Past Due 30-89d: Other Consumer Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK043: { label: 'Past Due 90d+: Other Consumer Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK044: { label: 'Nonaccrual: Other Consumer Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK102: { label: 'Past Due 30-89d: Lease Fin. Receivables (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK103: { label: 'Past Due 90d+: Lease Fin. Receivables (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK104: { label: 'Nonaccrual: Lease Fin. Receivables (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK105: { label: 'Lns Rstr C&I US Addr, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK106: { label: 'Lns Rstr C&I US Addr, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK107: { label: 'Lns Rstr C&I US Addr, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK108: { label: 'Lns Rstr C&I Non-US Addr, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK109: { label: 'Lns Rstr C&I Non-US Addr, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK110: { label: 'Lns Rstr C&I Non-US Addr, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK111: { label: 'Lns Rstr All Other Lns/Leases, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK112: { label: 'Lns Rstr All Other Lns/Leases, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK113: { label: 'Lns Rstr All Other Lns/Leases, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK114: { label: 'Itemize Ag Finance Farm, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK115: { label: 'Itemize Ag Finance Farm, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK116: { label: 'Itemize Ag Finance Farm, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK117: { label: 'Credit Card Ln Household Family, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK118: { label: 'Credit Card Ln Household Family, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK119: { label: 'Credit Card Ln Household Family, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK120: { label: 'Past Due 30-89d: Lns to Foreign Govts (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK121: { label: 'Past Due 90d+: Lns to Foreign Govts (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK122: { label: 'Nonaccrual: Lns to Foreign Govts (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK123: { label: 'Past Due 30-89d: All Other Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK124: { label: 'Past Due 90d+: All Other Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK125: { label: 'Nonaccrual: All Other Loans (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK126: { label: 'Repl Cost Contracts, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK127: { label: 'Repl Cost Contracts, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK128: { label: 'Repl Cost Contracts, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK130: { label: 'Auto Ln to Individual HH Family, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK131: { label: 'Auto Ln to Individual HH Family, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK132: { label: 'Auto Ln to Individual HH Family, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK138: { label: 'Purch Credit-Impr Ln Bal, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK139: { label: 'Purch Credit-Impr Ln Bal, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK140: { label: 'Purch Credit-Impr Ln Bal, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK213: { label: 'Purch Credit-Impr Ln Carry, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK214: { label: 'Purch Credit-Impr Ln Carry, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK215: { label: 'Purch Credit-Impr Ln Carry, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK216: { label: 'Lns Guar US Excl FDIC, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK217: { label: 'Lns Guar US Excl FDIC, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK218: { label: 'Lns Guar US Excl FDIC, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK257: { label: 'Other Ln to Ind HH Fam, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RCONK258: { label: 'Other Ln to Ind HH Fam, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RCONK259: { label: 'Other Ln to Ind HH Fam, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RCONK274: { label: 'GNMA Rebooked Lns Repurchased, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK275: { label: 'GNMA Rebooked Lns Repurchased, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK276: { label: 'GNMA Rebooked Lns Repurchased, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK277: { label: 'Loss-Share FDIC All Other Lns, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK278: { label: 'Loss-Share FDIC All Other Lns, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK279: { label: 'Loss-Share FDIC All Other Lns, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK280: { label: 'Loss-Share FDIC Covered, Past Due 30-89d (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK281: { label: 'Loss-Share FDIC Covered, Past Due 90d+ (Dom)', category: CATEGORIES.PAST_DUE },
  RCONK282: { label: 'Loss-Share FDIC Covered, Nonaccrual (Dom)', category: CATEGORIES.PAST_DUE },
  RCONPV23: { label: 'Audit Indicator (Dom)', category: CATEGORIES.OTHER },
  RCONPV24: { label: 'Fiscal Year End (Dom)', category: CATEGORIES.OTHER },
  RCONPV25: { label: 'Last Submission Accepted (Dom)', category: CATEGORIES.OTHER },

  // ── RIAD (Income Statement) ───────────────────────────────────────
  RIAD0093: { label: 'Interest Expense on Deposits', category: CATEGORIES.INCOME },
  RIAD3196: { label: 'Net Interest Income', category: CATEGORIES.INCOME },
  RIAD3521: { label: 'Provision for Loan & Lease Losses', category: CATEGORIES.INCOME },
  RIAD4010: { label: 'Total Interest & Fee Income on Loans', category: CATEGORIES.INCOME },
  RIAD4012: { label: 'Interest Income: Loans Secured by RE', category: CATEGORIES.INCOME },
  RIAD4020: { label: 'Interest Income: State & Local Obligations', category: CATEGORIES.INCOME },
  RIAD4024: { label: 'Other Interest Income', category: CATEGORIES.INCOME },
  RIAD4056: { label: 'Total Interest Income', category: CATEGORIES.INCOME },
  RIAD4058: { label: 'Interest on Time Deposits $100K+', category: CATEGORIES.INCOME },
  RIAD4059: { label: 'Interest on Time Deposits < $100K', category: CATEGORIES.INCOME },
  RIAD4060: { label: 'Interest on Deposits in Foreign Offices', category: CATEGORIES.INCOME },
  RIAD4065: { label: 'Interest on Other Borrowed Money', category: CATEGORIES.INCOME },
  RIAD4069: { label: 'Interest on Subordinated Notes & Debentures', category: CATEGORIES.INCOME },
  RIAD4070: { label: 'Total Interest Expense', category: CATEGORIES.INCOME },
  RIAD4073: { label: 'Net Interest Income After Provision', category: CATEGORIES.INCOME },
  RIAD4074: { label: 'Income Before Discontinued Operations', category: CATEGORIES.INCOME },
  RIAD4079: { label: 'Service Charges on Deposit Accounts', category: CATEGORIES.INCOME },
  RIAD4080: { label: 'Other Noninterest Income', category: CATEGORIES.INCOME },
  RIAD4092: { label: 'Total Noninterest Income', category: CATEGORIES.INCOME },
  RIAD4093: { label: 'Salaries & Employee Benefits', category: CATEGORIES.INCOME },
  RIAD4107: { label: 'Premises & Equipment Expense', category: CATEGORIES.INCOME },
  RIAD4115: { label: 'Other Noninterest Expense', category: CATEGORIES.INCOME },
  RIAD4135: { label: 'Total Noninterest Expense', category: CATEGORIES.INCOME },
  RIAD4150: { label: 'Pre-Tax Net Income', category: CATEGORIES.INCOME },
  RIAD4172: { label: 'Realized Gains (Losses) on Held-to-Maturity Securities', category: CATEGORIES.INCOME },
  RIAD4180: { label: 'Applicable Income Taxes', category: CATEGORIES.INCOME },
  RIAD4185: { label: 'Deferred Tax (Credit) / Charge', category: CATEGORIES.INCOME },
  RIAD4200: { label: 'Net Income (RIAD4200)', category: CATEGORIES.INCOME },
  RIAD4217: { label: 'Cash Dividends Declared on Common Stock', category: CATEGORIES.INCOME },
  RIAD4300: { label: 'Net Charge-Offs on Loans & Leases', category: CATEGORIES.INCOME },
  RIAD4301: { label: 'Net Charge-Offs on C&I Loans', category: CATEGORIES.INCOME },
  RIAD4302: { label: 'Net Charge-Offs on Installment Loans', category: CATEGORIES.INCOME },
  RIAD4313: { label: 'Net Charge-Offs on Real Estate Loans', category: CATEGORIES.INCOME },
  RIAD4340: { label: 'Net Income', category: CATEGORIES.INCOME },
  RIAD4435: { label: 'Interest Income on Trading Assets', category: CATEGORIES.INCOME },
  RIAD4436: { label: 'Interest Expense on Trading Liabilities', category: CATEGORIES.INCOME },
  RIAD4507: { label: 'Net Charge-Offs: Credit Card Loans', category: CATEGORIES.INCOME },
  RIAD4508: { label: 'Net Charge-Offs: Consumer Installment Loans', category: CATEGORIES.INCOME },
  RIAD4513: { label: 'Net Charge-Offs: Loans to Farmers', category: CATEGORIES.INCOME },
  RIAD4518: { label: 'Net Charge-Offs: RE Construction & Development', category: CATEGORIES.INCOME },
  RIAD5415: { label: 'Net Charge-Offs: Other Loans', category: CATEGORIES.INCOME },
  RIAD5416: { label: 'Net Charge-Offs: Other Leases', category: CATEGORIES.INCOME },
  RIAD8431: { label: 'Net Charge-Offs: RE Residential', category: CATEGORIES.INCOME },
  RIAD8757: { label: 'Net Charge-Offs: RE Multifamily', category: CATEGORIES.INCOME },
  RIAD8758: { label: 'Net Charge-Offs: RE Nonfarm Nonresidential', category: CATEGORIES.INCOME },
  RIAD8759: { label: 'Net Charge-Offs: RE Farmland', category: CATEGORIES.INCOME },
  RIAD8760: { label: 'Net Charge-Offs: C&I to Foreign Institutions', category: CATEGORIES.INCOME },
  RIAD9106: { label: 'Net Charge-Offs: Revolving Credit Card Plans', category: CATEGORIES.INCOME },
  RIADA220: { label: 'Interest Income: Balances Due from Dep. Inst.', category: CATEGORIES.INCOME },
  RIADA251: { label: 'Interest Income: Loans to Foreign Govts & Official Inst.', category: CATEGORIES.INCOME },
  RIADA530: { label: 'Cash Dividends Declared on Preferred Stock', category: CATEGORIES.INCOME },
  RIADB485: { label: 'Net Charge-Offs: Open-End RE Loans', category: CATEGORIES.INCOME },
  RIADB486: { label: 'Net Charge-Offs: 1st Lien RE Loans', category: CATEGORIES.INCOME },
  RIADB487: { label: 'Net Charge-Offs: Jr Lien RE Loans', category: CATEGORIES.INCOME },
  RIADB488: { label: 'Net Charge-Offs: Auto Loans to Individuals', category: CATEGORIES.INCOME },
  RIADB489: { label: 'Net Charge-Offs: Other Consumer Loans', category: CATEGORIES.INCOME },
  RIADB491: { label: 'Net Charge-Offs: Purchased Credit-Improved Loans', category: CATEGORIES.INCOME },
  RIADB492: { label: 'Net Charge-Offs: Loans to DIs', category: CATEGORIES.INCOME },
  RIADB493: { label: 'Net Charge-Offs: Foreign Banks', category: CATEGORIES.INCOME },
  RIADB496: { label: 'Net Charge-Offs: Loans Guaranteed by US Govt (Excl FDIC)', category: CATEGORIES.INCOME },
  RIADB497: { label: 'Net Charge-Offs: GNMA Rebooked Loans', category: CATEGORIES.INCOME },
  RIADC216: { label: 'Income from Fiduciary Activities', category: CATEGORIES.INCOME },
  RIADC232: { label: 'Other Noninterest Income (detail)', category: CATEGORIES.INCOME },
  RIADC386: { label: 'Net Gains on Sales of Loans & Leases', category: CATEGORIES.INCOME },
  RIADC387: { label: 'Net Gains on Sales of Other Real Estate Owned', category: CATEGORIES.INCOME },
  RIADC886: { label: 'Interest Income: C&I Loans to US Addresses', category: CATEGORIES.INCOME },
  RIADC887: { label: 'Interest Income: C&I Loans to Non-US Addresses', category: CATEGORIES.INCOME },
  RIADC888: { label: 'Interest Income: Consumer Credit Card Loans', category: CATEGORIES.INCOME },
  RIADC889: { label: 'Interest Income: Auto Loans to Individuals', category: CATEGORIES.INCOME },
  RIADC890: { label: 'Interest Income: Other Consumer Loans', category: CATEGORIES.INCOME },
  RIADF186: { label: 'Interest Income: Lease Financing Receivables', category: CATEGORIES.INCOME },
  RIADF551: { label: 'Net Charge-Offs: Loss-Share FDIC All Other Lns', category: CATEGORIES.INCOME },
  RIADF552: { label: 'Net Charge-Offs: Loss-Share FDIC Covered', category: CATEGORIES.INCOME },
  RIADF553: { label: 'Net Charge-Offs: Guar Lns Excl Rebook GNMA', category: CATEGORIES.INCOME },
  RIADF554: { label: 'Net Charge-Offs: Rebook GNMA Lns Repurchased', category: CATEGORIES.INCOME },
  RIADFT28: { label: 'Net Charge-Offs: Loans to Foreign Govts', category: CATEGORIES.INCOME },
  RIADFT36: { label: 'Net Charge-Offs: All Other Loans', category: CATEGORIES.INCOME },
  RIADFT37: { label: 'Net Charge-Offs: Lease Individual HH/Family', category: CATEGORIES.INCOME },
  RIADFT38: { label: 'Net Charge-Offs: All Other Leases', category: CATEGORIES.INCOME },
  RIADFT39: { label: 'Interest Income: RE Loans (Schedule RI-B)', category: CATEGORIES.INCOME },
  RIADFT40: { label: 'Interest Income: Construction & Land Dev Loans', category: CATEGORIES.INCOME },
  RIADG103: { label: 'Net Charge-Offs: RE Loans Secured by Farmland', category: CATEGORIES.INCOME },
  RIADG104: { label: 'Net Charge-Offs: Loans to Finance Agric Prod', category: CATEGORIES.INCOME },
  RIADGW44: { label: 'Net Charge-Offs: C&I Loans to US Addr', category: CATEGORIES.INCOME },
  RIADH032: { label: 'Itemize Auto Ln HH Family, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RIADH033: { label: 'Itemize Auto Ln HH Family, Past Due 90d+', category: CATEGORIES.PAST_DUE },
  RIADH034: { label: 'Itemize Auto Ln HH Family, Nonaccrual', category: CATEGORIES.PAST_DUE },
  RIADH035: { label: 'Other Consumer Ln HH Family, Past Due 30-89d', category: CATEGORIES.PAST_DUE },
  RIADHK03: { label: 'Net Charge-Offs: Credit Card Lns Household', category: CATEGORIES.INCOME },
  RIADHK04: { label: 'Net Charge-Offs: Auto Lns Household', category: CATEGORIES.INCOME },
  RIADHT69: { label: 'Interest Income: RE Multifamily Loans', category: CATEGORIES.INCOME },
  RIADHT70: { label: 'Interest Income: RE Nonfarm Nonresidential', category: CATEGORIES.INCOME },
  RIADHT73: { label: 'Interest Income: 1-4 Family RE Loans', category: CATEGORIES.INCOME },
  RIADHT74: { label: 'Interest Income: Home Equity Lines', category: CATEGORIES.INCOME },
  RIADJJ33: { label: 'Net Charge-Offs: Other Consumer Lns Household', category: CATEGORIES.INCOME },
};

module.exports = { CATEGORIES, KEY_METRICS, FIELD_MAP };
